// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fwgnljlzzpneinawyeqq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ3Z25samx6enBuZWluYXd5ZXFxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE3ODEwOTYsImV4cCI6MjA4NzM1NzA5Nn0.j7y4IRh6TNfwO4uVno5tZ9do7J6CmWuXbNNg3SIHqIc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});